### ISSUE TITLE
other tiny libs :)

### ISSUE THREAD

**Issue by leeoniya** [umbrellajs/umbrella#10]
check out:

https://github.com/finom/bala
https://github.com/finom/balalaika

**Comment by franciscop** [comment]
Hey thanks for sharing, I like what they can do. However [the source code](https://github.com/finom/bala/blob/master/bala.js) for [both](https://github.com/finom/balalaika/blob/master/balalaika.js) looks like a nightmare to maintain

**Comment by eorroe** [comment]
https://github.com/eorroe/NodeList.js

**Comment by nono** [comment]
And what do you think of [Bliss.js](http://blissfuljs.com/) ?

**Comment by franciscop** [comment]
@nono I really like it, I'm reading the source to see how I could help since there are few concepts that I haven't used before :smile:

**Comment by eorroe** [comment]
@nono, not sure if you care about my opinion, but I don't like bliss.js It seems like a tiny jQuery which there are multiple of them. I think the [most famous](https://github.com/remy/min.js) one by Remy.

They are just methods that are like jQuery, but just the ones that people want, which eventually will just get bigger and bigger, sort of being like jQuery because most methods you'll never use.

**Of Course it won't get as much popularity as jQuery though**

**Comment by franciscop** [comment]
@eorroe I am not sure that's the case everywhere. While you refer to Bliss, I was afraid that this could also happen to Umbrella so I asked the same to myself many times.

The problem (that I think) jquery has is a huge technical debt. It was made back in the day of IE6, and while some things have been deleted in newer versions, it's far from getting rid of al of it.

There are many example, but just to point one, check `addClass()` (also note that Umbrella's `addClass()` is much more flexible):

[Umbrella JS](https://github.com/umbrellajs/umbrella/blob/master/src/plugins/addclass/addclass.js):

```js
u.prototype.addClass = function(){
  
  // Loop the combination of each node with each argument
  return this.eacharg(arguments, function(el, name){
    
    // Add the class using the native method
    el.classList.add(name);
  });
};
```

[jQuery](https://github.com/jquery/jquery/blob/a4d16a26abe3ea36337f7bfc4d1bfe13b893cd17/src/attributes/classes.js#L15):

```js
	addClass: function( value ) {
		var classes, elem, cur, curValue, clazz, j, finalValue,
			i = 0;

		if ( jQuery.isFunction( value ) ) {
			return this.each( function( j ) {
				jQuery( this ).addClass( value.call( this, j, getClass( this ) ) );
			} );
		}

		if ( typeof value === "string" && value ) {
			classes = value.match( rnotwhite ) || [];

			while ( ( elem = this[ i++ ] ) ) {
				curValue = getClass( elem );
				cur = elem.nodeType === 1 &&
					( " " + curValue + " " ).replace( rclass, " " );

				if ( cur ) {
					j = 0;
					while ( ( clazz = classes[ j++ ] ) ) {
						if ( cur.indexOf( " " + clazz + " " ) < 0 ) {
							cur += clazz + " ";
						}
					}

					// Only assign if different to avoid unneeded rendering.
					finalValue = jQuery.trim( cur );
					if ( curValue !== finalValue ) {
						elem.setAttribute( "class", finalValue );
					}
				}
			}
		}

		return this;
	},
```

In this example in particular, jquery uses `setAttribute` instead of `className` or `classList`, which are more modern but [not retro-compatible](http://caniuse.com/#search=classList)

So the main difference is that libraries like jquery have focused in compatibility (which they maintain), while Umbrella is focused on size, so there are many reusable and size-optimized parts. Both ways have their advantages/disadvantages, but if I wanted to use a library like jquery with support like jquery's, then I wouldn't have created Umbrella :smile:

**Comment by eorroe** [comment]
Disclosure: I'm not even a fan of jQuery as you can see from [my library](www.sitepoint.com/dom-manipulation-with-nodelist-js/)

Like you said jQuery is focused on compatibility, so yea that's why its complex, but what happens is since its so popular, and widely known, cached almost on everyone's computer, and cdns people tend not to care about the size etc, and just use what they need, also if they really do care about the size, but still want to use jQuery just without the bloat there are tools out there that allow you to take out the pieces of jQuery you do want, and you can serve that to your users.

But yea take a look at my library, and if you like it you'll notice you might not need anything else, because whenever browsers add new methods, my library will pick it up.

**Comment by franciscop** [comment]
@eorroe this is really nice:

```js
$$('button').textContent = 'Click Me';
```

Does it come from here?

```js
set: function( value ) {
    for( var i = 0, l = this.length, el; i < l; i++ ) {
        el = this[ i ];
        if( el && prop in el ) el[ prop ] = value;
    }
}
```

I've only tried something like that [in Umbrella with `.length`](https://github.com/umbrellajs/umbrella/blob/master/src/umbrella.js#L20) so far, but it's really interesting :smile:

**Comment by eorroe** [comment]
Yup it comes from there
