### ISSUE TITLE
Why this name "umbrella"?

### ISSUE THREAD

**Issue by huei90** [umbrellajs/umbrella#11]
any reason?

![umbrella](http://i0.wp.com/hopeliesat24framespersecond.files.wordpress.com/2013/07/15.jpg)

**Comment by franciscop** [comment]
Yeah, a funny one actually. Umbrella started first just as a wrapper for document.querySelector (to convert it to an array) such as:

```js
function(selector){
  var list = document.querySelectorAll(selector);
  return Array.prototype.slice.call(list);
}
```

But as you can see, there's no name for the function. I didn't feel comfortable using `$()` since *it is not jquery*, so I tried searching what characters I could use. Turns out any "letter", but special characters only `$` and `_` (both of which were overused).

So from any "letter" you could also use other languages. At some point it was `ñ()` (I'm Spanish) and some greek character, but this was not very international. Then, just trying it, this also worked perfectly:

```js
var ☂ = function(selector) { ... }
☂(".whatever");
```

I was playing for it for a time before deciding it was just too strange, but the umbrella remained in my head. Later when I was drawing I realized how much the stick in an umbrella resembles a "J", so I just added an "S" and it became Umbrella JS with the current logo :smile:

![umbrella](https://cloud.githubusercontent.com/assets/2801252/12530838/be598e24-c1eb-11e5-9903-e1329a41fbb3.png)

**Comment by huei90** [comment]
:100: Thanks for your explaination. Great feedback :+1: 

I personally like ☂

```js
var ☂ = function(selector) { ... }
☂(".whatever");
```

Until now, just understanding the meaning of the logo :laughing: "J"S

**Comment by franciscop** [comment]
Thanks :smile:
