### ISSUE TITLE
Is there any specific functions that dont work in IE10? 

### ISSUE THREAD

**Issue by code-mattclaffey** [umbrellajs/umbrella#39]
Is there any specific functions that dont work in IE10? If not should'nt the documentation say support for IE10 plus? Just because if the javascript works in IE10 then the support covers it?

I am doing a talk on this in a few days so it would be nice to know a little information about what features do not work in IE10? 

Thank you

**Comment by franciscop** [comment]
Hi @code-mattclaffey ,

The tests all pass now on IE10 as you said since IE10 and IE11 APIs are quire similar. However, the official support is only for IE11+. What this means is that bugfixes will only happen for issues present in IE11+. These might come from an issue, a new test or different ways, but they only need to be tested (to check if solved) in IE11.

But it's also about semver, since a breaking change for IE10 is not considered a breaking change since the browser is not supported. However if we break something with IE11, Firefox, Chrome, etc then a major release is expected. That part is more of a moral contract with the developers.

Of course all of this is kind of flexible; if there's a new bug in an unsupported browser, but the change is minimal and it fixes the bug, why not? Sure I'll add it.

PS, what is the talk on? Javascript libraries browser support?

**Comment by code-mattclaffey** [comment]
Hi @franciscop my talk is about using Umbrella.js for modern applications. Listing out the cons and the IE11+ support is one of them for the company I work for. 

I have added how to use a fallback for IE8-9 its just IE10. 

Based on your comment then I can just say all tests pass in IE10 and IE11 and to add a fallback for older browsers use jquery (with conditional comments) and assign he u variable to equal the dollar. 

Really awesome plugin though. Saved a second load time on my website.

**Comment by franciscop** [comment]
Oh that's a pity, and thank you so much for rooting for Umbrella JS!!

Also please note that it is **not** a jQuery clone; it doesn't even have the same methods. It has a subset *and* some extra functions that make some common tasks easier. So it highly depends on what features you want/need. [See this relevant conversation](https://news.ycombinator.com/item?id=10954428) on adding the `$` by default:

>  I like it! Since it's a jQuery alternative, I wonder if you've considered having the global name default to "$" rather than "u"? 
>  It was somewhere in the documentation but I took that off deliberately since it's not really 100% compatible, so it'd just confuse people long-term.

**Comment by code-mattclaffey** [comment]
Okay brilliant! Keep up with the good work. :) :+1:

**Comment by franciscop** [comment]
How was it? I'm closing this issue at the moment, but feel free to ask anything else here or on a new issue :+1:

**Comment by code-mattclaffey** [comment]
It went really well thank you :) @franciscop
