### ISSUE TITLE
.slice(): Force a parameter to become an array AND also it clones them

### ISSUE THREAD

**Issue by tr3intaydos** [umbrellajs/umbrella#44]
I was looking at the code for ajax( ) and find that 'little hack'.
it could be eliminated my adding this at [umbrella.js:31](https://github.com/umbrellajs/umbrella/blob/master/src/umbrella.js#L31)

```js
Object.prototype.toString.call(parameter).indexOf("Array") === -1
```

```js
// If we're referring a specific node as in on('click', function(){ u(this) })
// or the select() function returned a single node such as in '#id'
if (parameter && (parameter.nodeName || Object.prototype.toString.call(parameter).indexOf("Array") === -1)) {
  parameter = [parameter];
}
```

but i don't see another use beside that.
will it be helpful?

**Comment by franciscop** [comment]
But that would be similar to doing `Array.isArray(parameter)`. Which has an important problem:

If we pass an string to `.slice()` it gets blown up into `['h', 'e', 'l', 'l', 'o']`. Ideally `.slice()` should return an array of the converted object if it is a pseudo-array, or it would just do `parameter = [parameter]` otherwise (such as an string, your example, or just about any other thing).

So I have been looking for a method to detect pseudo-arrays and integrating it into `.slice()`, but it wasn't a priority right now for me because the current method "works". However if you can find some way of detecting a pseudo-array, please add it :+1:

**Comment by franciscop** [comment]
See [this StackOverflow answer](http://stackoverflow.com/a/24048615/938236) for why this is an issue right now.

**Comment by tr3intaydos** [comment]
Underscore uses these for checking for Arrays, Objects and Functions: 

```js
toString = Object.prototype.toString;

_.isArray = nativeIsArray || function(obj) {
  return toString.call(obj) == '[object Array]';
};

_.isObject = function(obj) {
  return obj === Object(obj);
};

_.isFunction = function(obj) {
  return toString.call(obj) == '[object Function]';
};
```

([source](https://github.com/jashkenas/underscore/blob/master/underscore.js#L1281))

**Comment by franciscop** [comment]
Yes but we don't want to check if it's array. We also want to slice `arguments` and `NodeList`, for example, which are not arrays BUT they can be converted to array. So we need to detect "array-like", not just array. See the answer in StackOverflow I linked.

**Comment by tr3intaydos** [comment]
```js
u.prototype.slice = function(pseudo) {
  // Accept also a u() object (that has .nodes)
  return isArrayLike(pseudo) ? [].slice.call(pseudo.nodes || pseudo) : [pseudo];
};
```

```js
function isArrayLike(obj) {
  if (!obj) return false;
  var l = obj.length;
  if (typeof l != 'number' || l < 0) return false;
  if (Math.floor(l) != l) return false;
  if (l>0 && !((l-1) in obj)) return false;
  for (var i=0; i<l; ++i) {
    if (!(i in obj)) return false;
  }
  return true;
}
```

Test cases
Passes:
```js
u([request])
u(request)
u([document])
u(document)
u('html')
u(['html','script'])
u(nodelist)
u(function())
u([])
u(arguments)
```

Fails:
```js
u([[]])
u(map)
u(set)
```

**Comment by franciscop** [comment]
That looks awesome. Do you mind explaining why some edge cases are needed?

```js
function isArrayLike(obj) {
  if (!obj) return false;
  var l = obj.length;

  // When can .length be below 0?
  if (typeof l != 'number' || l < 0) return false;

  // When can .length be a fraction? [1]
  if (Math.floor(l) != l) return false;

  // What does this check? Isn't it the same as the next one? [2]
  if (l>0 && !((l-1) in obj)) return false;

  // Why do we need this? [3]
  for (var i=0; i<l; ++i) {
    if (!(i in obj)) return false;
  }
  return true;
}
```

We don't really want to accept:

- Strings
- Functions
- Simple objects `{ a: 'b' }`

So these should **not** pass:

```js
u('html')
u(function())
u({})
```

**Comment by franciscop** [comment]
Note that ignoring Map and Set is okay for this case: they are not used internally, not so common and not documented as usable. So if you pass them to Umbrella don't expect anything beautiful to happen happen. `.slice()` itself is for internal use only. Also note that this could be checked:

```js
if (!length) return false;
```

Since an array with length 0 is the same as `[]`, which is the value predefined by `.slice()`.

**Comment by franciscop** [comment]
Fixed in https://github.com/umbrellajs/umbrella/commit/3a8aab7abba9330cedf7f33163337a44f62d58e8

**Comment by tr3intaydos** [comment]
its all it needs. it was for checking for sparse arrays and checking for not number keys, nor negative key array (Its a thing).
