### ISSUE TITLE
API Addition - Pass event context explicitly

### ISSUE THREAD

**Issue by tracker1** [umbrellajs/umbrella#46]
It would be nice, if the event context were passed explicitly as an alternative, or in conjunction with "this", would be better imho, since 'this' and 'eval' can be considered dangerous, as they can't be traced in a non-running context.  It's been a niggle of mine with jQuery for a number of years.

```
$('button').on('click', function(evt, button) {
  button = $(button);
})
```

**Comment by franciscop** [comment]
I actually added it since I don't know if `this` would be passed with ES6's arroy functions. However I deleted it for two reasons:

- The `button` is actually passed inside `evt` as `currentTarget`:

```js
u('button').on('click', function(evt, button) {
  button = u(evt.currentTarget);
});
```

- The second and further parameters <strike>are</strike> should be `data` passed through `.trigger()`

```js
u('button').on('click', function(e, jimmy, johnny){ /* ... */ });

var jim = 20, john = 30;
u('button').trigger('click', jim, john);
```

However I completely forgot to implement+document it on the `.on()` side, while it *is* impemented on the `.trigger()` side.

**Comment by franciscop** [comment]
Update on the bug found from this request: now `.on()` callback accepts the data as parameters.
