### ISSUE TITLE
.ajax() doesn't check for form validation in Safari 9.1

### ISSUE THREAD

**Issue by cprecioso** [umbrellajs/umbrella#53]
When sending a form with validation, `.ajax()` doesn't check it

- Tested in
  * Safari 9.1 (possibly Safari Mobile too) - no checks happen
  * Safari Developer Preview 9.1.1 - no checks happen
  * Chrome latest - it prevents form sending
  * Firefox latest - it prevents form sending

- Example
```html
<form id="the-form" action="#"><input type="text" required /><input type="submit" /></form>
```
```js
u("#the-form").ajax(function(){
  alert("Sent!")
})
```
When trying to send the form blank, `.ajax()` shouldn't fire. It does in Safari.

**Comment by franciscop** [comment]
Test case: https://jsfiddle.net/franciscop/Lh5dfa1L/

Confirmed with Safari on BrowserStack. Possible solution: http://stackoverflow.com/a/23261375/938236

**Comment by franciscop** [comment]
It apparently [also happens in jQuery](https://jsfiddle.net/franciscop/deyraofw/) and there's no easy fix, since the fix depends completely on each specific interface as seen in [this polyfill example](https://github.com/aFarkas/webshim#installation-and-usage). Good browsers show a notification, and just doing a `.preventDefault()` without showing a notice to the user would be really bad for the UX.

So validation has to be done per-case, possibly using that polyfill mentioned. The problem is that [Safari doesn't support the attribute *required*](http://caniuse.com/#search=required)
