### ISSUE TITLE
event delegation through .on()

### ISSUE THREAD

**Issue by yomed** [umbrellajs/umbrella#63]
Hi, this looks like a really useful project! I noticed that there is no mention of event delegation in the code or issues in the repo. Was this feature ever considered? It looks like that would be only thing that's missing for me to migrate some projects straight away. I realize you can delegate manually, but the easy delegation in jquery and similar libraries is great shorthand.

```js
u('.parent').on('click', '.child', function () {
   ...
}
```

**Comment by franciscop** [comment]
I am not sure I'm qualified to do this. Even simple events have few edge cases, such as remembering the callback for the `off()`, so I always thought that event delegation would introduce too much nastiness.

I might just try the naive solution, adding a wrapping callback that handles it if the second parameter is a string. Also I will check other APIs to try not to go too far away from them.

**Comment by ianwhitedeveloper** [comment]
@franciscop maybe [this resource](http://bdadam.com/blog/plain-javascript-event-delegation.html) could be helpful? I'm looking into this for the dom node event issue I've run into for my other [pull request](https://github.com/umbrellajs/umbrella/pull/62).

**Comment by franciscop** [comment]
Yeah @ianwhitedeveloper, that's basically what I was thinking. But then `.off()` would only work on the original parent which is a bit weird (but it's okay and follows jQuery way). I think it's weird because the event fires when `click`ing a button, but you cannot do `u('button').off('click');`

So it would just be like doing it manually with that code, with the convenience of being a default way but with the problem that it would not be customizable. But I think I'm okay with that. @yomed would that also work for you?

**Comment by yomed** [comment]
Thanks for looking into it. I would expect that behavior since you are still explicitly setting the event on the parent, so it would make sense if you had to remove it from the parent as well.

**Comment by franciscop** [comment]
There is an obvious bug, it will trigger with any other child. I'll update it soon.

**Comment by franciscop** [comment]
Should be fixed now according to the tests. Might have missed something, so feel free to update it with any problem/bug you find :smile:
