### ISSUE TITLE
add .toggleClass()

### ISSUE THREAD

**Issue by themadcreator** [umbrellajs/umbrella#7]
Please consider adding the jquery method .toggleClass. It is one of the most used jquery methods in many code bases I've worked on for its simple ability to use a boolean to set whether or not an element has a class.

Otherwise, everyone using your library will likely have to continually write code like:

```javascript
let toggle = true;

if (toggle && !u("div").hasClass("super-awesome-class")) {
  u("div").addClass("super-awesome-class");
} else if (!toggle && u("div").hasClass("super-awesome-class")) {
  u("div").removeClass("super-awesome-class");
}
```

When you could just have:

```javascript
let toggle = true;
u("div").toggleClass("super-awesome-class", toggle);
```

Would you accept a PR with this feature?

**Comment by franciscop** [comment]
Sure! Initially I thought against it, since I don't really use it, but I realize many people might use it so bring it on (:

**Comment by franciscop** [comment]
However, it's safe to simplify your code to this:

```js
let toggle = true;

if (toggle) {
  u("div").addClass("super-awesome-class");
} else {
  u("div").removeClass("super-awesome-class");
}
```

Since addClass and removeClass just won't do anything if it's not needed. There is just one question left unanswered, but the most important one I think: **what's the function footprint?**. Because:

- addClass accepts 0-N parameters
- removeClass accepts 0-N parameters
- hasClass accepts 0-N parameters
- toggleClass accepts ? parameters

For this, there are really two options:

1. it accepts 2 parameters, the first might be space, comma separated or an array (similar to `.on()` and jquery) and the second parameter is `toggle`
2. it accepts 0-N parameters, and if the last one is a boolean then it follows that (more similar to other Umbrella *class* methods, and also convenient)

Note that the second is an extension of the first, but it'd be quite more complex in the code. However, the first one feels more limited and might make it not so intuitive. I am inclined to go with the first option, but what do you think?

**Comment by themadcreator** [comment]
Awesome thanks!
