### ISSUE TITLE
More useful context in callback of .on() function

### ISSUE THREAD

**Issue by aishikaty** [umbrellajs/umbrella#77]
This has been changed in commit 34c304c470f95d85e81cfca18ab86f43f8d6ecec.
I would prefer to keep the target as context really. Consider this example:

```javascript
u(document).on("click", "a[data-ajax-load]", function (ev) {
  var url = u(this).attr("href")
  // ... ajax load the url
})
```
I use it this way a lot in jQuery and it seems very natural to me. I know I can use `.closest()` to get the link again but that seems like a extra step when we already have it. Also the real click target is always there in `ev.target` when I need it.

BTW: thank you for such an awesome library.

**Comment by franciscop** [comment]
I think it's better to stop relying on and thinking about `this` for ES5 and ES6 since with them it's much better to pass it all through the parameters. This is vanilla ES6:

```js
var doubleletter = ['a', 'b', 'c'].map(a => a + a);
```

And with Umbrella you'd have it really similar:

```js
var doubleletter = u(['a', 'b', 'c']).map(a => a + a);
```

While with jQuery-style loops you'd have something like this:

```js
var doubleletter = $(['a', 'b', 'c']).map((i, a) => a + a);
```

Which is the opposite to vanilla JS (and Umbrella JS). Of course this wouldn't work, because in an Arrow Function `this` makes no sense:

```js
var doubleletter = $(['a', 'b', 'c']).map(i => this + this);
```

Now if you are using Umbrella JS you probably know all of that, so this is relevant because we want Umbrella to be ES6 & ES5 friendly and teaching best practices. While the case above is clear and straightforward, the one at hand is a lot more difficult sinice the `<a>` is not being passed now.

Your code could be written as:

```js
u(document).on("click", "a[data-ajax-load]", function (ev) {
  var url = u(this).closest("a[data-ajax-load]").attr("href");
  // ... ajax load the url
})
```

Which is WET and ugly code, even in it's ES6 version:

```js
u(document).on("click", "a[data-ajax-load]",
  e => ajax(u(e.target).closest('a[data-ajax-load]').attr('href'), {},
    (err, data) => alert(data)
  )
})
```

But at *least* they have the same implementations in ES5 and ES6 (even though they are not so good). I'm totally open to more suggestions, but please try to take into account the ES6-forward thinking.

PS, I'm still trying to decide which one is *less* evil, changing the prototype or add yet another `target`-like element (`this`) to the mixture.

**Comment by franciscop** [comment]
To sum up using `this`:

PROS:

- Similar to jQuery
- DRY code
- Simpler code

CONS:

- First? time that `this` is **needed** in Umbrella JS; so
- Not ES6-compatible
- Even more confusing (`e.target`, `e.currentTarget`, and `this` might be different elements)

Both PROs and CONs are quite strong TBH, for consistence I gravitated towards not using `this` but again any input is welcome.

**Comment by aishikaty** [comment]
Thanks @franciscop for such a great response. I see now why you don't like to use `this`. I tried how jQuery behaves and it seems to be setting the `e.currentTarget` to the same value as `this`.
Eg: `$(document).on("click", "a", cb)` on clicking to element inside `<a>` has both - the `this` and `e.currentTarget` set to the `<a>` tag. I'm not exactly sure how they change the value of the `currentTarget` property as it's read-only.
What do you think about that? Would it be good solution if it's possible to change that property?

**Comment by franciscop** [comment]
Okay, I'll try to do a couple of tests this weekend to see how jQuery works internally. Read-only can be forged easily in a flexible language as javascript (just copy the object for example).

**Comment by franciscop** [comment]
I dug a bit into it. [For this HTML](https://jsfiddle.net/kxjzqxpt/):

```html
<ul>
  <li>
    <a>Hi</a>
  </li>
</ul>
```

And this javascript (similar in both jQuery):

```javascript
u('ul.b').on('click', 'li', function(e){
	console.log(e.target, e.currentTarget, this);
});
```

jQuery shows this on console:

```html
<a> <li> <li>
```

While Umbrella shows this:

```html
<a> <ul> <a>
```


e.target seems the same and [the definition for e.target](https://developer.mozilla.org/en-US/docs/Web/API/Event/target) is correct for both:

> A reference to the object that dispatched the event. It is different from event.currentTarget when the event handler is called during the bubbling or capturing phase of the event.

Now [the definition for e.currentTarget](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget) is:

> Identifies the current target for the event, as the event traverses the DOM. It always refers to the element the event handler has been attached to as opposed to event.target which identifies the element on which the event occurred.

Because there is no native delegation, the issue stems from the interpretation of *It always refers to the element the event handler has been attached to*. In Umbrella JS the event is literally attached on the `ul` for our previous case, but it delegates (which doesn't exist in the spec) the calls.

In jQuery the event is *also* attached to the `ul`, however they make this call more transparent and it behaves the same as if it was attached to the delegated element. I'll dig into jQuery code to see how they are doing it. You can see how they both are really attached into the `ul` here:

![attached](https://cloud.githubusercontent.com/assets/2801252/17337144/c13f4bbe-58e1-11e6-9487-0b96b7bc218c.png)

So it boils down to: let's follow the spec literally even for a situation where it's not supposed to be defined (delegation) or let's do it more convenient even if *lying* on the low level.

**Comment by franciscop** [comment]
I am already [this deep into it](https://jsfiddle.net/kxjzqxpt/8/) and now I'd have to basically copy all of the properties. I am not so sure anymore whether it's worth it or not to continue that path, but we definitely need to be able to retrieve the matched element..

jQuery copies each of the properties: [event.js line 595](https://github.com/jquery/jquery/blob/master/src/event.js#L595)

**Comment by aishikaty** [comment]
Oh, good job. Yes, that probably doesn't worth it.

I prefer `ev.currentTarget` to be set to matched element even if it's not in specs. When I'm delegating I don't care about the element on which I have the listener (it's usually `document`).

I found that it's possible to change the read-only value with `defineProperty`, at least in Chrome. So following code has same output as jQuery.
```html
<ul id="ul">
  <li>
    <a id="a">Hi</a>
  </li>
</ul>

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script>

  function on(el, type, sel, cb) {
    el.addEventListener(type, function(ev) {
      var target = ev.target.closest(sel)
      if (target) {
        Object.defineProperty(ev, 'currentTarget', {
          value: target
        })
        cb.call(target, ev)
      }
    })
  }
  
  $(ul).on("click", "li", function (ev) {
    console.log(ev.target, ev.currentTarget, this)
  })
  on(ul, "click", "li", function(ev) {
    console.log(ev.target, ev.currentTarget, this)
  })

  a.click()
  
</script>
```
In both cases output is: `<a>`, `<li>`, `<li>`.

Although I'm not sure if it's alright to overwrite it like that and if it works cross-browser.
What do you think about it?

**Comment by aishikaty** [comment]
Please ignore the code above. I just tried in other browsers and the `defineProperty` trick doesn't work in IE :(.

**Comment by franciscop** [comment]
Okay that is way cleaner and easier than what I was trying to do, thank you. It should be also easy to test, do you want to make a PR with that code? Otherwise I will do it as soon as possible.

**Comment by franciscop** [comment]
This still has the issue of being unable to detach a single event or a single group of events with `.off()`:

```js
u(document).on('click', '.demo1', ...);
u(document).on('click', '.demo2', ...);
u(document).on('click', '.demo3', ...);

// Doesn't do anything
u('.demo2').off('click');

// Removes all of them
u(document).off('click');
```

However, it's normally not recommended to bind the listener in the `u(document)` but doing it in the ancestor of the selector that you know won't mutate if the page is large-ish for performance (fewer elements to check). It is a smaller/secondary issue in my opinion so no problem with that as long as we document it.

This should be working already:

https://jsfiddle.net/kxjzqxpt/9/

**Comment by aishikaty** [comment]
Awesome. Thank you @franciscop.

**Comment by franciscop** [comment]
No problem, it *fails* in PhantomJS 1.9.8 because that webkit is old so I expect it to fail in some older browsers. I still need to test where since right now it's a fatal error.
