### ISSUE TITLE
${ fruit } wont work

### ISSUE THREAD

**Issue by englishextra** [umbrellajs/umbrella#78]
Well I tested with electron and had required babel-polyfill

```
require("babel-polyfill");

/*!
 * umbrellajs.com/documentation#home
 */
var u = require('umbrellajs').u;
var fruits = ['apple', 'strawberry', 'pear', 'banana'];
var list = u('<ul>').append(fruit => '<li>${ fruit }</li>', fruits);

u('body').append(list);
```
And the output throws a ul list but ES6 variables didnt get converted:

```
${ fruit }
${ fruit }
${ fruit }
${ fruit }
```
Please provide a full code so that it could be obvious that the framework works. Too many bugs in issues.

**Comment by franciscop** [comment]
You are using a normal string `''` instead of an ES6 string template `\`\``, so it's normal that they are not converted. Change that line to this and it shouls work:

```
var list = u('<ul>').append(fruit => `<li>${ fruit }</li>`, fruits);
```

Also, Electron is not officially supported and please be polite while asking for help instead of demanding full code as neither me nor the occasional Umbrella JS maintainers are working for you.
